services:
  redis:
    image: redis:latest
    container_name: redis_chat
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: golang_chat
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: ["go", "run", "main.go"]
    depends_on:
      - redis

volumes:
  redis_data: